#!/bin/bash
d=`dirname $0`
cd $d
dir=`pwd`
if [ "$1" == "make" ]; then
	mkdir lib/cfg.d/
	ln -sf ../../cfg/cfg.d/z_plumx.pl lib/cfg.d/z_plumx.pl
	ln -sf lib/cfg.d/ 
	ln -sf lib/static/
	ln -sf lib/lang/
	ln -sf lib/plugins/
elif [ "$1" == "unmake" ]; then
	rm -f plugins
	rm -f lang
	rm -f static
	rm -f cfg.d
	rm -f lib/cfg.d/z_plumx.pl
	rmdir lib/cfg.d/
fi
if ls $dir/../../flavours/*/inc 1> /dev/null 2>&1; then 
	touch $dir/../../flavours/*/inc
fi
exit 0
